// Code generated by logcopter-gen; DO NOT EDIT.

package git

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.prescribe.cmd.prescribe.cmds.context.git")
